### ISSUE TITLE
Edit egg list adding egg dont work 

### ISSUE THREAD

**Issue by Devitsune** [M6D6M6A/PokeRogueBot#2]
Hi, when i try to add some eggs it don't work bu i still have the message that eggs got generated and uploaded but in game there is nothing. 
But the command replace work nice :)
![Capture d’écran 2024-05-30 102551](https://github.com/M6D6M6A/PokeRogueBot/assets/137762751/3260cdda-612d-461a-b83f-a2a478c6daf4)
![Capture d’écran 2024-05-30 102758](https://github.com/M6D6M6A/PokeRogueBot/assets/137762751/fa6dc8ef-8ec2-4e8b-92fd-586cc2d55f06)

**Comment by M6D6M6A** [comment]
Yea, correct it was a bug again, I used `.append(list)` instead of `.extend(list)`, so I added the list to the list instead of adding the elements of one list to the other. Please close the issue if it works now, and thanks for your time writing the issue. :)

**Comment by Devitsune** [comment]
It work nice thx :)

**Comment by Devitsune** [comment]
It work nice thx :)
